/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.gestion;

/**
 *
 * Esta clase representa el inicio de la aplicación.
 ** <p>
 * Contiene la inicialización de componentes gráficos y la configuración inicial
 * </p>
 *
 * @author emont
 * @version 1.0
 */
public class Inicio extends javax.swing.JDialog {

    /**
     * Creates new form Inicio
     */
    public Inicio(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        jLabel_bienvenida = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        kButton_entrar = new com.k33ptoo.components.KButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        kGradientPanel1.setkBorderRadius(0);
        kGradientPanel1.setkEndColor(new java.awt.Color(0, 102, 102));
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 102, 102));

        jLabel_bienvenida.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel_bienvenida.setForeground(new java.awt.Color(247, 249, 253));
        jLabel_bienvenida.setText("Gestión de gastos");

        jLabel1.setIcon(new javax.swing.ImageIcon("G:\\Mi unidad\\DESARROLLO DE INTERFACES\\EJERCICIOS\\imgs\\moneda.png")); // NOI18N

        kButton_entrar.setBorder(null);
        kButton_entrar.setText("Entrar");
        kButton_entrar.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        kButton_entrar.setkBackGroundColor(new java.awt.Color(157, 37, 50));
        kButton_entrar.setkEndColor(new java.awt.Color(255, 204, 0));
        kButton_entrar.setkHoverColor(new java.awt.Color(190, 96, 0));
        kButton_entrar.setkHoverEndColor(new java.awt.Color(190, 96, 0));
        kButton_entrar.setkHoverForeGround(new java.awt.Color(239, 239, 239));
        kButton_entrar.setkHoverStartColor(new java.awt.Color(190, 96, 0));
        kButton_entrar.setkIndicatorColor(new java.awt.Color(109, 37, 50));
        kButton_entrar.setkPressedColor(new java.awt.Color(133, 78, 45));
        kButton_entrar.setkSelectedColor(new java.awt.Color(133, 78, 45));
        kButton_entrar.setkStartColor(new java.awt.Color(190, 96, 0));
        kButton_entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton_entrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_bienvenida)
                .addGap(55, 55, 55))
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(kButton_entrar, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel_bienvenida)))
                .addGap(56, 56, 56)
                .addComponent(kButton_entrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
     * Este método es invocado cuando se produce un evento de acción en el botón
     * de entrar. Realiza las siguientes acciones: <ul><li>Crea una nueva
     * instancia de la clase Ventana y la posiciona en el centro.</li>
     * <li>2. Cierra la ventana actual.</li>
     * <li>3. Hace visible la nueva ventana creada.</li>
     * </ul>
     *
     * @param evt El evento de acción que desencadenó la llamada a este método.
     */
    private void kButton_entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton_entrarActionPerformed
        Ventana v = new Ventana();
        v.setLocationRelativeTo(null);

        dispose();
        v.setVisible(true);
    }//GEN-LAST:event_kButton_entrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Inicio dialog = new Inicio(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                //hacemos que aparezca en el centro
                dialog.setLocationRelativeTo(null);
                dialog.setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_bienvenida;
    private com.k33ptoo.components.KButton kButton_entrar;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    // End of variables declaration//GEN-END:variables
}
